name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      - name: Run Server Tests
        working-directory: ./server
        run: npm test

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run build

      # Example of deploying to Netlify (uncomment and configure as needed)
      # - name: Deploy to Netlify
      #   uses: netlify/actions/deploy@v1
      #   with:
      #     publishDir: './client/build'
      #     netlifyToken: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     siteId: ${{ secrets.NETLIFY_SITE_ID }}
